name: 'run tests'

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '19'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run build
      run: |
        ./gradlew build